services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  finance.web:
    image: finance.web
    build:
      context: .
      dockerfile: Finance.Web/Dockerfile

  finance.infra:
    image: finance.infra
    build:
      context: .
      dockerfile: Finance.Infra/Dockerfile

  finance.tests:
    image: finance.tests
    build:
      context: .
      dockerfile: test/Finance.tests/Dockerfile
