name: Restrict PRs to Master

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Pull requests para a branch master só são permitidos a partir da develop."
            exit 1
          fi
